name: Google Play 리뷰 슬랙 자동 보고

on:
  schedule:
    # 매일 오전 9시(한국시간, UTC+9) → UTC 0시
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  report:
    runs-on: ubuntu-latest
    env:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      GOOGLE_PLAY_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python (3.13)
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-api-python-client google-auth requests

      - name: Set up secrets files
        run: |
          mkdir -p .secrets
          echo "$SLACK_BOT_TOKEN" > .secrets/slack_bot_token.txt
          echo "$GOOGLE_PLAY_SERVICE_ACCOUNT_KEY" > .secrets/google_play_service_account_key.json

      - name: Run Google Play 리뷰 슬랙 자동 보고
        run: |
          python send_google_play_review_report.py
